SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/database/Downloads/homework1sampledata.dat".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/02/2020 
22:36:37.355376".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3191W  The field in row "F0-1", column "7" which begins with ""1995-01-01"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-1" of 
the input file.

SQL3191W  The field in row "F0-2", column "7" which begins with ""2003-10-10"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-2" of 
the input file.

SQL3191W  The field in row "F0-3", column "7" which begins with ""2005-04-05"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-3" of 
the input file.

SQL3191W  The field in row "F0-4", column "7" which begins with ""1979-08-17"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-4" of 
the input file.

SQL3191W  The field in row "F0-5", column "7" which begins with ""2003-09-14"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-5" of 
the input file.

SQL3191W  The field in row "F0-6", column "7" which begins with ""2005-09-30"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-6" of 
the input file.

SQL3191W  The field in row "F0-7", column "7" which begins with ""2000-08-15"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-7" of 
the input file.

SQL3191W  The field in row "F0-8", column "7" which begins with ""2000-06-19"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-8" of 
the input file.

SQL3191W  The field in row "F0-9", column "7" which begins with ""1988-05-16"" 
does not match the user specified DATEFORMAT, TIMEFORMAT, or TIMESTAMPFORMAT. 
The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-9" of 
the input file.

SQL3191W  The field in row "F0-10", column "7" which begins with 
""1993-12-05"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-10" 
of the input file.

SQL3191W  The field in row "F0-11", column "7" which begins with 
""2001-07-28"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-11" 
of the input file.

SQL3191W  The field in row "F0-12", column "7" which begins with 
""2006-12-15"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-12" 
of the input file.

SQL3191W  The field in row "F0-13", column "7" which begins with 
""2002-02-12"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-13" 
of the input file.

SQL3191W  The field in row "F0-14", column "7" which begins with 
""2006-10-11"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-14" 
of the input file.

SQL3191W  The field in row "F0-15", column "7" which begins with 
""1999-09-15"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-15" 
of the input file.

SQL3191W  The field in row "F0-16", column "7" which begins with 
""2003-07-07"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-16" 
of the input file.

SQL3191W  The field in row "F0-17", column "7" which begins with 
""2004-07-26"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-17" 
of the input file.

SQL3191W  The field in row "F0-18", column "7" which begins with 
""2002-03-03"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-18" 
of the input file.

SQL3191W  The field in row "F0-19", column "7" which begins with 
""1998-04-11"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-19" 
of the input file.

SQL3191W  The field in row "F0-20", column "7" which begins with 
""1998-08-29"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-20" 
of the input file.

SQL3191W  The field in row "F0-21", column "7" which begins with 
""1996-11-21"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-21" 
of the input file.

SQL3191W  The field in row "F0-22", column "7" which begins with 
""2004-12-05"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-22" 
of the input file.

SQL3191W  The field in row "F0-23", column "7" which begins with 
""1999-10-30"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-23" 
of the input file.

SQL3191W  The field in row "F0-24", column "7" which begins with 
""2005-09-11"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-24" 
of the input file.

SQL3191W  The field in row "F0-25", column "7" which begins with 
""2006-09-30"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-25" 
of the input file.

SQL3191W  The field in row "F0-26", column "7" which begins with 
""1997-03-24"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-26" 
of the input file.

SQL3191W  The field in row "F0-27", column "7" which begins with 
""2006-05-30"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-27" 
of the input file.

SQL3191W  The field in row "F0-28", column "7" which begins with 
""2002-06-19"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-28" 
of the input file.

SQL3191W  The field in row "F0-29", column "7" which begins with 
""1994-09-12"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-29" 
of the input file.

SQL3191W  The field in row "F0-30", column "7" which begins with 
""1995-07-07"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-30" 
of the input file.

SQL3191W  The field in row "F0-31", column "7" which begins with 
""2006-02-23"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-31" 
of the input file.

SQL3191W  The field in row "F0-32", column "7" which begins with 
""1977-05-05"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-32" 
of the input file.

SQL3191W  The field in row "F0-33", column "7" which begins with 
""1995-01-01"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-33" 
of the input file.

SQL3191W  The field in row "F0-34", column "7" which begins with 
""2002-05-05"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-34" 
of the input file.

SQL3191W  The field in row "F0-35", column "7" which begins with 
""2006-12-15"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-35" 
of the input file.

SQL3191W  The field in row "F0-36", column "7" which begins with 
""2005-09-15"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-36" 
of the input file.

SQL3191W  The field in row "F0-37", column "7" which begins with 
""2005-08-29"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-37" 
of the input file.

SQL3191W  The field in row "F0-38", column "7" which begins with 
""2004-12-05"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-38" 
of the input file.

SQL3191W  The field in row "F0-39", column "7" which begins with 
""1997-03-24"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-39" 
of the input file.

SQL3191W  The field in row "F0-40", column "7" which begins with 
""1994-09-12"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-40" 
of the input file.

SQL3191W  The field in row "F0-41", column "7" which begins with 
""2006-02-23"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-41" 
of the input file.

SQL3191W  The field in row "F0-42", column "7" which begins with 
""1997-07-05"" does not match the user specified DATEFORMAT, TIMEFORMAT, or 
TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "F0-42" 
of the input file.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3227W  Record token "F0-2" refers to user record number "2".

SQL3227W  Record token "F0-3" refers to user record number "3".

SQL3227W  Record token "F0-4" refers to user record number "4".

SQL3227W  Record token "F0-5" refers to user record number "5".

SQL3227W  Record token "F0-6" refers to user record number "6".

SQL3227W  Record token "F0-7" refers to user record number "7".

SQL3227W  Record token "F0-8" refers to user record number "8".

SQL3227W  Record token "F0-9" refers to user record number "9".

SQL3227W  Record token "F0-10" refers to user record number "10".

SQL3227W  Record token "F0-11" refers to user record number "11".

SQL3227W  Record token "F0-12" refers to user record number "12".

SQL3227W  Record token "F0-13" refers to user record number "13".

SQL3227W  Record token "F0-14" refers to user record number "14".

SQL3227W  Record token "F0-15" refers to user record number "15".

SQL3227W  Record token "F0-16" refers to user record number "16".

SQL3227W  Record token "F0-17" refers to user record number "17".

SQL3227W  Record token "F0-18" refers to user record number "18".

SQL3227W  Record token "F0-19" refers to user record number "19".

SQL3227W  Record token "F0-20" refers to user record number "20".

SQL3227W  Record token "F0-21" refers to user record number "21".

SQL3227W  Record token "F0-22" refers to user record number "22".

SQL3227W  Record token "F0-23" refers to user record number "23".

SQL3227W  Record token "F0-24" refers to user record number "24".

SQL3227W  Record token "F0-25" refers to user record number "25".

SQL3227W  Record token "F0-26" refers to user record number "26".

SQL3227W  Record token "F0-27" refers to user record number "27".

SQL3227W  Record token "F0-28" refers to user record number "28".

SQL3227W  Record token "F0-29" refers to user record number "29".

SQL3227W  Record token "F0-30" refers to user record number "30".

SQL3227W  Record token "F0-31" refers to user record number "31".

SQL3227W  Record token "F0-32" refers to user record number "32".

SQL3227W  Record token "F0-33" refers to user record number "33".

SQL3227W  Record token "F0-34" refers to user record number "34".

SQL3227W  Record token "F0-35" refers to user record number "35".

SQL3227W  Record token "F0-36" refers to user record number "36".

SQL3227W  Record token "F0-37" refers to user record number "37".

SQL3227W  Record token "F0-38" refers to user record number "38".

SQL3227W  Record token "F0-39" refers to user record number "39".

SQL3227W  Record token "F0-40" refers to user record number "40".

SQL3227W  Record token "F0-41" refers to user record number "41".

SQL3227W  Record token "F0-42" refers to user record number "42".

SQL3110N  The utility has completed processing.  "42" rows were read from the 
input file.

SQL3519W  Begin Load Consistency Point. Input record count = "42".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/02/2020 
22:36:37.442790".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 42
Number of rows skipped      = 0
Number of rows loaded       = 0
Number of rows rejected     = 42
Number of rows deleted      = 0
Number of rows committed    = 42

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/database/Downloads/homework1sampledata.dat".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/02/2020 
22:40:31.846264".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "42" rows were read from the 
input file.

SQL3519W  Begin Load Consistency Point. Input record count = "42".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/02/2020 
22:40:31.897504".


Number of rows read         = 42
Number of rows skipped      = 0
Number of rows loaded       = 42
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 42

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/database/Downloads/homework1sampledata.dat".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/03/2020 
01:36:26.248581".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "42" rows were read from the 
input file.

SQL3519W  Begin Load Consistency Point. Input record count = "42".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/03/2020 
01:36:26.294688".


Number of rows read         = 42
Number of rows skipped      = 0
Number of rows loaded       = 42
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 42

