SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/database/Downloads/arcos-ny-statewide-itemized.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "02/22/2020 
06:44:24.555341".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3119W  The value in row "1" and column "9" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "1" and column "19" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "1" and column "22" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3123W  The field value in row "1" and column "25" cannot be converted to a 
PACKED DECIMAL value.  A null was loaded.

SQL3191W  The field in row "1", column "31" which begins with 
"TRANSACTION_DATE" does not match the user specified DATEFORMAT, TIMEFORMAT, 
or TIMESTAMPFORMAT. The row will be rejected.

SQL3185W  The previous error occurred while processing data from row "1" of 
the input file.

SQL3123W  The field value in row "9480" and column "33" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3123W  The field value in row "2938537" and column "33" cannot be converted 
to a PACKED DECIMAL value.  A null was loaded.

SQL3123W  The field value in row "4807443" and column "33" cannot be converted 
to a PACKED DECIMAL value.  A null was loaded.

SQL3123W  The field value in row "7207532" and column "33" cannot be converted 
to a PACKED DECIMAL value.  A null was loaded.

SQL3123W  The field value in row "7227975" and column "33" cannot be converted 
to a PACKED DECIMAL value.  A null was loaded.

SQL3123W  The field value in row "8257680" and column "33" cannot be converted 
to a PACKED DECIMAL value.  A null was loaded.

SQL3110N  The utility has completed processing.  "11402094" rows were read 
from the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "11402094".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "02/22/2020 
06:50:18.649215".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 11402094
Number of rows skipped      = 0
Number of rows loaded       = 11402093
Number of rows rejected     = 1
Number of rows deleted      = 0
Number of rows committed    = 11402094

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/database/Downloads/nyzip.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "02/23/2020 
00:12:31.204716".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3119W  The value in row "F0-1" and column "1" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "F0-1" and column "2" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "F0-1" and column "3" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "F0-1" and column "4" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3110N  The utility has completed processing.  "44411" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "44411".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "02/23/2020 
00:12:31.301381".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 44411
Number of rows skipped      = 0
Number of rows loaded       = 44411
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 44411

SQL3304N  The table does not exist.

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/database/Downloads/nyzip.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/05/2020 
23:16:12.762014".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3119W  The value in row "F0-1" and column "1" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "F0-1" and column "2" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "F0-1" and column "3" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3119W  The value in row "F0-1" and column "4" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3110N  The utility has completed processing.  "44411" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "44411".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/05/2020 
23:16:12.866288".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 44411
Number of rows skipped      = 0
Number of rows loaded       = 44411
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 44411

